CREATE PROCEDURE [dbo].[sp_get_configuration_by_key]
    @CONFIGURATION_KEY NVARCHAR(100)
AS
BEGIN
    SELECT [CONFIGURATION_VALUE]
    FROM Configuration
    WHERE [CONFIGURATION_KEY] = @CONFIGURATION_KEY;
END;
