CREATE PROCEDURE [dbo].[sp_set_configuration_key_value]
    @CONFIGURATION_KEY NVARCHAR(100),
    @CONFIGURATION_VALUE NVARCHAR(MAX),
    @IS_ENCRYPTED BIT = 0
AS
BEGIN
    IF EXISTS (SELECT 1 FROM Configuration WHERE CONFIGURATION_KEY = @CONFIGURATION_KEY)
    BEGIN
        UPDATE Configuration 
        SET CONFIGURATION_VALUE = @CONFIGURATION_VALUE,
            IS_ENCRYPTED = @IS_ENCRYPTED
        WHERE CONFIGURATION_KEY = @CONFIGURATION_KEY;
        
        SELECT 1; -- Success
    END
    ELSE
    BEGIN
        INSERT INTO Configuration (CONFIGURATION_KEY, CONFIGURATION_VALUE, IS_ENCRYPTED)
        VALUES (@CONFIGURATION_KEY, @CONFIGURATION_VALUE, @IS_ENCRYPTED);
        
        SELECT 1; -- Success
    END
END;